CC=gcc
CCFLAGS=
LINKER_DEBUG=$(CC) $(CCFLAGS) -o
LINKER_RELEASE=$(CC) $(CCFLAGS) -O3 -o
TARGET=main
TARGET_DIR=target
TARGET_DEBUG=$(TARGET_DIR)/$(TARGET)_debug
TARGET_RELEASE=$(TARGET_DIR)/$(TARGET)_release
SRC_DIR=src
LIB_DIR=$(SRC_DIR)/lib
MAIN_FILE=$(SRC_DIR)/main.c
LIB_FILES=$(wildcard $(LIB_DIR)/*.c)
SRC_FILES=$(MAIN_FILE) $(LIB_FILES)
.DEFAULT_GOAL:= debug
debug:$(TARGET_DEBUG)
$(TARGET_DEBUG):$(SRC_FILES) $(TARGET_DIR)
	$(LINKER_DEBUG) $@ $(SRC_FILES)
$(TARGET_DIR):
	mkdir $@
release:$(TARGET_RELEASE)
$(TARGET_RELEASE):$(SRC_FILES) $(TARGET_DIR)
	$(LINKER_RELEASE) $@ $(SRC_FILES)
clean:
	rm -r $(TARGET_DIR)
run:$(TARGET_DEBUG)
	./$<
r_run:$(TARGET_RELEASE)
	./$<
